### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Just-In-Web** [mydnic/WebRadioVisualizer#2]
Hello,

it's not working with my Icecast.. 
My StreamURL is: http://icecast.z8r.de/bigmusicradio-mp3

Nothing works.. What can I do?

**Comment by mydnic** [comment]
Did you correctly add the http headers in your icecast config file ?
```
<http-headers>
    <header name="Access-Control-Allow-Origin" value="*" />
....
</http-headers>
```

**Comment by Just-In-Web** [comment]
Yes,
but I think it was Icecast 2.3, on Icecast 2.4 it works.

**Comment by mydnic** [comment]
yep 2.4 is required :)
Cheers
